#!/bin/sh
# Prints the Homebrew cask for a release. The release workflow commits the
# output to the Jleagle/homebrew-coffee tap as Casks/coffee.rb.
#
#   cask.sh <version> <sha256-of-tarball>
set -eu

VERSION="$1"
SHA256="$2"

cat <<CASK
# Generated by cask.sh in Jleagle/coffee on each release. DO NOT EDIT.
cask "coffee" do
  version "${VERSION}"
  sha256 "${SHA256}"

  url "https://github.com/Jleagle/coffee/releases/download/v#{version}/coffee_#{version}_darwin_all.tar.gz"
  name "Coffee"
  desc "Menu bar app for ordering from the coffee shop"
  homepage "https://github.com/Jleagle/coffee"

  livecheck do
    skip "Updated by the release workflow."
  end

  # Matches LSMinimumSystemVersion in bundle.sh.
  depends_on macos: :ventura

  app "Coffee.app"

  postflight_steps do
    on_macos do
      # Ad-hoc signed, not notarized — strip the quarantine flag or Gatekeeper
      # blocks the first launch.
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/Coffee.app"], must_succeed: false
      # (Re)launch, so an upgrade restarts the app.
      run "/usr/bin/open", args: ["-a", "{{appdir}}/Coffee.app"], must_succeed: false
    end
  end

  # Quit the running app before an upgrade/uninstall replaces it.
  uninstall quit: "com.jleagle.coffee"
end
CASK
