#!/bin/sh
# Prints the Homebrew formula for a release. The release workflow commits the
# output to the Jleagle/homebrew-coffee tap as Formula/coffee.rb, where brew
# compiles Coffee.app from the tagged source on the user's machine.
#
#   formula.sh <version> <sha256-of-source-tarball>
set -eu

VERSION="$1"
SHA256="$2"

case "$VERSION" in
  *[!0-9.]*|.*|*.|"") echo "formula.sh: bad version '$VERSION' (expected e.g. 1.2.3)" >&2; exit 1 ;;
esac

cat <<FORMULA
# Generated by homebrew/formula.sh in Jleagle/coffee on each release. DO NOT EDIT.
class Coffee < Formula
  desc "Menu bar app for ordering from the coffee shop"
  homepage "https://github.com/Jleagle/coffee"
  url "https://github.com/Jleagle/coffee/archive/refs/tags/v${VERSION}.tar.gz"
  sha256 "${SHA256}"

  livecheck do
    skip "Updated by the release workflow."
  end

  depends_on xcode: ["15.0", :build]
  # Matches LSMinimumSystemVersion in bundle.sh.
  depends_on macos: :ventura

  def install
    # Homebrew already sandboxes the build and SwiftPM's own sandbox cannot
    # nest inside it.
    system "swift", "build", "-c", "release", "--disable-sandbox"
    # Info.plist + ad-hoc codesign live in bundle.sh, shared with run.sh.
    system "./bundle.sh", ".build/release/coffee-menubar", version.to_s, "Coffee.app"
    prefix.install "Coffee.app"
  end

  # The app used to live in /Applications as a cask. From the Cellar,
  # \`brew services start coffee\` is what runs it at login.
  service do
    run [opt_prefix/"Coffee.app/Contents/MacOS/coffee-menubar"]
    # Relaunch after a crash, but stay quit when quit from the menu bar.
    keep_alive successful_exit: false
    log_path var/"log/coffee.log"
    error_log_path var/"log/coffee.log"
  end

  # Homebrew adds its own \`brew services start coffee\` hint after this.
  def caveats
    <<~EOS
      Coffee.app lives in the Cellar, not /Applications. To run it once:
        open #{opt_prefix}/Coffee.app

      After \`brew upgrade coffee\`, restart it to pick up the new version:
        brew services restart coffee
    EOS
  end

  test do
    assert_match "<string>#{version}</string>", (prefix/"Coffee.app/Contents/Info.plist").read
  end
end
FORMULA
